onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - workerd

overrides:
  '@vitejs/plugin-rsc@<=0.5.2': '>=0.5.3'
  '@vitejs/plugin-rsc@<=0.5.5': '>=0.5.6'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
