allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@4.20260525.1'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - workerd
