name: ADR
description: 'Architecture Decision Record (ADR)'
title: '[ADR]: '
body:
  - type: input
    id: adr-deciders
    attributes:
      label: 'Deciders'
      description: 'The GitHub handles of the people who approved or rejected the ADR. To be completed retrospectively once an outcome is decided.'

  - type: textarea
    id: adr-context
    attributes:
      label: 'Context and Problem Statement'
      description: 'Describe the context and problem statement. You may want to articulate the problem in form of a question.'
      placeholder: 'What are we going to do about x?'
    validations:
      required: true

  - type: textarea
    id: adr-drivers
    attributes:
      label: 'Decision Drivers'
      description: 'What drivers/requirements did you evaluate the options against?'
      placeholder: '1. Performance'
    validations:
      required: false

  - type: textarea
    id: adr-options
    attributes:
      label: 'Considered Options'
      description: 'List all the options that were considered'
      value: |
        1. [option 1]
        2. [option 2]
        3. [option 3]
        4. … <!-- number of options can vary -->
    validations:
      required: true

  - type: textarea
    id: adr-pros-cons
    attributes:
      label: 'Pro and Cons of the Options'
      description: 'List all the options that were considered'
      value: |
        ### [option 1]

        [example | description | pointer to more information | …] <!-- optional -->

        * 🟢 Provides benefits
        * 🔴 Increases complexity
        * … <!-- numbers of pros and cons can vary -->

        ### [option 2]

        [example | description | pointer to more information | …] <!-- optional -->

        * 🟢 Provides benefits
        * 🔴 Increases complexity
        * … <!-- numbers of pros and cons can vary -->

        ### [option 3]

        [example | description | pointer to more information | …] <!-- optional -->

        * 🟢 Provides benefits
        * 🔴 Increases complexity
        * … <!-- numbers of pros and cons can vary -->
    validations:
      required: true

  - type: textarea
    id: adr-decision
    attributes:
      label: 'Decision Outcome'
      description: 'Describe the proposal in as much detail as needed for reviewers to give concrete feedback.'
      value: |
        ### Option 1: Do the thing
        We decided this was the best approach to take because [justification. e.g., only option, which meets k.o. criterion decision driver | which resolves force force | … | comes out best (see below)]
    validations:
      required: true

  - type: textarea
    id: adr-pos-consequences
    attributes:
      label: 'Positive Consequences'
      description: 'What are the positive consequences?'
      placeholder: 'Improvement of quality attribute satisfaction, follow-up decisions required, ...'
    validations:
      required: false

  - type: textarea
    id: adr-neg-consequences
    attributes:
      label: 'Negative Consequences'
      description: 'Does this decision have any negative consequences?'
      placeholder: 'Compromising quality attribute, follow-up decisions required, ...'
    validations:
      required: false

  - type: textarea
    id: adr-links
    attributes:
      label: 'Links'
      description: 'Collate any external references here, e.g PRs, other ADRs, confluence pages etc.'
      placeholder: |
        * Refined by [ADR-0005](0005-example.md)
        * … <!-- numbers of links can vary -->
    validations:
      required: false
