name: Generate or Update ADR

on:
  issues:
    types: [closed, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  process-adr:
    if: |
      github.event.issue.state == 'closed' &&
      contains(github.event.issue.labels.*.name, 'adr')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate or update ADR file
        id: adr
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');
            const path = require('path');

            const issue = context.payload.issue;
            const issueNumber = issue.number.toString().padStart(4, '0');
            const rawTitle = issue.title.replace(/^\[ADR\]:?\s*/i, '');
            const slug = rawTitle.toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/^-|-$/g, '')
              .slice(0, 60);

            const branch = `adr/${issueNumber}-${slug}`;
            const filename = `docs/adr/${issueNumber}-${slug}.md`;
            const newContent = `# [ADR]: ${rawTitle}\n\n${issue.body}`;

            // Create and switch to branch
            execSync(`git checkout -B ${branch}`, { stdio: 'inherit' });

            // Read current content if file exists
            let currentContent = '';
            if (fs.existsSync(filename)) {
              currentContent = fs.readFileSync(filename, 'utf-8');
            }

            // Only write and commit if the content changed
            if (currentContent !== newContent) {
              fs.mkdirSync(path.dirname(filename), { recursive: true });
              fs.writeFileSync(filename, newContent);

              execSync(`git add "${filename}"`, { stdio: 'inherit' });
              execSync(`git commit -m "docs(adr): update ${filename}"`, { stdio: 'inherit' });
            } else {
              console.log('No changes to ADR file; skipping commit.');
            }

            core.setOutput('branch', branch);
            core.setOutput('filename', filename);

      - name: Push branch
        run: git push origin ${{ steps.adr.outputs.branch }}

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.adr.outputs.branch }}
          commit-message: 'docs(adr): update ${{ steps.adr.outputs.filename }}'
          title: 'docs(adr): update ${{ steps.adr.outputs.filename }}'
          body: 'ADR generated or updated from issue #${{ github.event.issue.number }}.'
          labels: adr
